export const LAYOUT_CHANGE = "LAYOUT_CHANGE";
export const TOKEN_AUTH = "TOKEN_AUTH";
export const COURSE_TRAINING_REGISTERATION_LOV_DATA =
  "COURSE_TRAINING_REGISTERATION_LOV_DATA";
export const USER_DATA = "USER_DATA";
export const SLIDER_DATA = "SLIDER_DATA";
export const SLIDER_DATA_TOTAL = "SLIDER_DATA_TOTAL";
export const NOTIFICATION_COUNTS = "NOTIFICATION_COUNTS";
export const MENU_SERVICE = "MENU_SERVICE";
